services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: rihal_de
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "rihal_de"]
      interval: 10s
      timeout: 5s
      retries: 5

  etl:
    build:
      context: .
      dockerfile: etl.Dockerfile
    depends_on:
      db:
        condition: service_healthy

  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_URL: postgresql://admin:admin@db:5432/rihal_de

volumes:
  pgdata:
